name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nttai1406/mongo-express-app:latest
      - name: Deploy to Render
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
          method: POST
          customHeaders: '{"Authorization": "Bearer ${{ secrets.RENDER_API_KEY }}"}'
